language: python
cache: pip
dist: xenial

python:
  - 2.7
  - 3.7

install:
  # - pip install -U pip setuptools setuptools_scm
  - pip install -r requirements.txt
  - pip install pytest ruamel.yaml pyyaml pandas numpy optuna==0.14.0

script:
  - export SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0
  - python setup.py test

branches:
  except:
    - docs
